project_id = "tgqfakfloonbunwkdoug"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.create-mp-preference]
    verify_jwt = false
  [functions.invite-user]
    verify_jwt = false
  [functions.mp-webhook]
    verify_jwt = false
  [functions.invite-admin]
    verify_jwt = false
  [functions.notify-student-update]
    verify_jwt = false
