
ALTER TABLE public.suscripciones 
  ADD COLUMN IF NOT EXISTS auto_renovacion BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS cancelada_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS cancelada_motivo TEXT DEFAULT NULL;
