name: FX test once

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/fx-test-once.yml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check runner
        run: echo "GitHub Actions available"
